# Версия формата docker-compose файла
version: '3.8'

# Определение сервисов (контейнеров) в нашем приложении
services:
  # Сервис бэкенда (FastAPI приложение)
  backend:
    build: ./backend     # Путь к Dockerfile для сборки образа
    ports:
      - "8000:8000"      # Проброс портов: хост:контейнер (8000 на хосте -> 8000 в контейнере)
    #volumes:                 volumes больше не нужен, так как модель копируется при сборке
    #  - ./model:/app/model
    restart: unless-stopped   # Политика перезапуска: перезапускать всегда, кроме ручной остановки

  # Сервис фронтенда (Streamlit приложение)
  frontend:
    build: ./frontend        # Путь к Dockerfile для сборки образа
    ports:
      - "8501:8501"          # Проброс портов: хост:контейнер (8501 на хосте -> 8501 в контейнере)

    depends_on:
      - backend              # Обеспечивает запуск backend перед frontend (но не ждет его готовности)

    restart: unless-stopped  # Политика перезапуска: перезапускать всегда, кроме ручной остановки